version: '3.0'

networks:
  app:
    driver: bridge

volumes:
  couchdb-data:
    driver: local

services:
  couchdb:
    image: couchdb:3.3.2
    networks:
      - app
    env_file:
      - .env.example
    environment:
      - COUCHDB_USER:${COUCHDB_USER}
      - COUCHDB_PASSWORD:${COUCHDB_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - couchdb-data:/opt/couchdb/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - couchdb
    env_file:
      - .env.example
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app