name: ALIAS-SOLVD-TEAM2 Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        # the path where the npm dependencies will be cached
        path: ~/.npm
        # key := platform + node-version + hash of the package-lock.json
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        # the exact key is not found => use the one that matches the node version
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test --if-present

